function [T]=FK3(Tbase,Ttool,q,t,L,l)
T=Tbase*Tx(l)*Tz(l)*Ty(q(9))*Ty(t(1))*Ry(q(10))*Tz(L)*Tx(t(2))*Ty(t(3))*Tz(t(4))...
    *Rx(t(5))*Ry(t(6))*Rz(t(7))*Ry(q(11))*Tz(L)...
    *Tx(t(8))*Ty(t(9))*Tz(t(10))*Rx(t(11))*Ry(t(12))*Rz(t(13))...
    *Ry(q(12))*Ttool;